---
permalink: intro-family.html
keywords: storagegrid
summary: The NetApp E-Series storage family offers flexible and cost-effective backup and recovery to the cloud, and is designed for dedicated, high-bandwidth applications that need simple, easy to manage, and fast block storage with enterprise-grade reliability.
---

= Learn about StorageGRID
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
The NetApp E-Series storage family offers flexible and cost-effective backup and recovery to the cloud, and is designed for dedicated, high-bandwidth applications that need simple, easy to manage, and fast block storage with enterprise-grade reliability.

== E-Series platforms
E-Series storage systems use application-aware, data management tools that can handle multiple drive types in either a 2U or 4U form factor. You can connect the storage system to a SAN from multiple interface types and to a variety of host operating systems.

E-Series storage systems include the following platform models.

=== EF600 and EF300
Designed specifically for workloads that demand the highest levels of performance such as big data analytics and databases.

https://docs.netapp.com/us-en/e-series/getting-started/learn-hardware-concept.html#ef600-models[Read more about the EF600 model].

https://docs.netapp.com/us-en/e-series/getting-started/learn-hardware-concept.html#ef300-models[Read more about the EF300 model].

https://www.netapp.com/pdf.html?item=/media/19339-DS-4082.pdf[Read the EF-Series Datasheet^].

=== E5700
Built for high-performance and data-intensive bandwidth applications with enterprise-grade reliability.

https://docs.netapp.com/us-en/e-series/getting-started/learn-hardware-concept.html#e5700-models[Read more about the E5700 model].

https://www.netapp.com/pdf.html?item=/media/7572-ds-3894.pdf[Read the E5700 Datasheet^].

=== E2800
Optimized for small enterprises and remote offices that require mixed-workload performance and reliability for dedicated apps.

https://docs.netapp.com/us-en/e-series/getting-started/learn-hardware-concept.html#e2800-models[Read more about the E2800 model].

https://www.netapp.com/pdf.html?item=/media/7573-ds-3805.pdf[Read the E2800 Datasheet^].

== SANtricity software

SANtricity software provides both the System Manager and Unified Manager web-based interfaces used for viewing, provisioning, and managing storage systems in your network.

https://www.netapp.com/pdf.html?item=/media/7676-ds-3891.pdf[Read the SANtricity software Datasheet^].

=== SANtricity System Manager

System Manager is web-based management software embedded on each controller. To access the user interface, point a browser to the controller’s IP address. A setup wizard helps you get started with system configuration.

* Intuitive workflow wizards and context-sensitive help streamline configuration tasks.

* The software suggests configuration candidates that take advantage of hardware capabilities such as drawer loss protection on dense enclosures, and smart management of wear life and performance on SSDs.

* Sophisticated performance monitoring lets you view information from the system level down to individual drives or export the performance data for further analysis.

* Tuning activities such as managing the SSD cache or data cache are all online. When a repair becomes necessary, the SANtricity Recovery Guru provides step-by-step instructions.

Go to the https://docs.netapp.com/us-en/e-series-santricity/system-manager/index.html[SANtricity System Manager doc site], where you can find information about how to plan, configure, manage, and troubleshoot your storage array.

=== SANtricity Unified Manager
Unified Manager is web-based software used for managing your entire domain. From a central view, you can see status for all newer E-Series and EF-Series arrays, such as the E2800, EF280, EF300, E5700, EF570, and EF600. You can also perform batch operations on selected storage arrays.

* From a single window, you can view status, organize arrays into groups, update the SANtricity OS for multiple arrays, and launch the on-box SANtricity System Manager for each array.

* You can quickly configure alerts and other settings to multiple arrays with a single operation.

* SANtricity Unified Manager is installed on a Linux or Windows management server and runs in a browser.

Go to the https://docs.netapp.com/us-en/e-series-santricity/unified-manager/index.html[SANtricity Unified Manager doc site], where you can learn how to execute storage management commands on multiple network storage arrays.

=== SANtricity Web Services Proxy
The Web Services Proxy is a full-function RESTful API server for orchestration and automation needs that can manage hundreds of new and legacy E-Series arrays. The proxy is installed separately on a Windows or Linux server. Web Services includes API documentation that allows you to directly interact with the REST API.

Access the https://docs.netapp.com/us-en/e-series/web-services-proxy/index.html[Web Services Proxy docs].

== CLI
The command line interface (CLI) is a software application that provides a way to configure and monitor storage arrays.

Using the CLI, you can run commands from an operating system prompt, such as the DOS C: prompt, a Linux operating system path, or a Solaris operating system path.

Go to the https://docs.netapp.com/us-en/e-series-cli/index.html[SANtricity CLI doc site], where you can learn how to configure and monitor your storage arrays using CLI commands.

== For more information

* https://docs.netapp.com/us-en/e-series/index.html[E-Series system docs^]
* https://docs.netapp.com/us-en/e-series-santricity/index.html[SANtricity software docs^]
* https://docs.netapp.com/us-en/e-series-cli/index.html[SANtricity CLI docs^]