---
permalink: intro-family.html
keywords: storagegrid
summary: NetApp StorageGRID is a software-defined object storage suite that supports a wide range of use cases across public, private, and hybrid multicloud environments. StorageGRID offers native support for the Amazon S3 API and delivers industry-leading innovations such as automated lifecycle management to store, secure, protect, and preserve unstructured data cost effectively over long periods.
---
= Learn about StorageGRID
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
NetApp StorageGRID is a software-defined object storage suite that supports a wide range of use cases across public, private, and hybrid multicloud environments. StorageGRID offers native support for the Amazon S3 API and delivers industry-leading innovations such as automated lifecycle management to store, secure, protect, and preserve unstructured data cost effectively over long periods.

StorageGRID provides secure, durable storage for unstructured data at scale. Integrated, metadata-driven lifecycle management policies optimize where your data lives throughout its life. Content is placed in the right location, at the right time, and on the right storage tier to reduce cost.

StorageGRID is composed of geographically distributed, redundant, heterogeneous nodes, which can be integrated with both existing and next-generation client applications.

== StorageGRID benefits

Advantages of the StorageGRID system include the following:

* Massively scalable and easy-to-use a geographically distributed data repository for unstructured data.
* Support for Amazon Web Services Simple Storage Service (S3) protocol

* Hybrid cloud enabled. Policy-based information lifecycle management (ILM) stores objects to public clouds, including Amazon Web Services (AWS) and Microsoft Azure. StorageGRID platform services enable content replication, event notification, and metadata searching of objects stored to public clouds.
* Flexible data protection to ensure durability and availability. Data can be protected using replication and layered erasure coding. At-rest and in-flight data verification ensures integrity for long-term retention.
* Dynamic data lifecycle management to help manage storage costs. You can create ILM rules that manage data lifecycle at the object level, and customize data locality, durability, performance, cost, and retention time.
* High availability of data storage and some management functions, with integrated load balancing to optimize the data load across StorageGRID resources.
* Support for multiple storage tenant accounts to segregate the objects stored on your system by different entities.
* Numerous tools for monitoring the health of your StorageGRID system, including a comprehensive alert system, a graphical dashboard, and detailed statuses for all nodes and sites.
* Support for software or hardware-based deployment. You can deploy StorageGRID on any of the following:

 ** Virtual machines running in VMware.
 ** Container engines on Linux hosts.
 ** StorageGRID engineered appliances. 
 *** Storage appliances provide object storage. 
 *** Services appliances provide grid administration and load balancing services.

* Compliant with the relevant storage requirements of these regulations:
 ** Securities and Exchange Commission (SEC) in 17 CFR ยง 240.17a-4(f), which regulates exchange members, brokers or dealers.
 ** Financial Industry Regulatory Authority (FINRA) Rule 4511(c), which defers to the format and media requirements of SEC Rule 17a-4(f).
 ** Commodity Futures Trading Commission (CFTC) in regulation 17 CFR ยง 1.31(c)-(d), which regulates commodity futures trading.
* Non-disruptive upgrade and maintenance operations. Maintain access to content during upgrade, expansion, decommission, and maintenance procedures.
* Federated identity management. Integrates with Active Directory, OpenLDAP, or Oracle Directory Service for user authentication. Supports single sign-on (SSO) using the Security Assertion Markup Language 2.0 (SAML 2.0) standard to exchange authentication and authorization data between StorageGRID and Active Directory Federation Services (AD FS).

== StorageGRID software

* https://docs.netapp.com/us-en/storagegrid-118/[StorageGRID 11.8 docs^]
* https://docs.netapp.com/us-en/storagegrid-117/[StorageGRID 11.7 docs^]
* https://docs.netapp.com/us-en/storagegrid-116/[StorageGRID 11.6 docs^]
* https://docs.netapp.com/us-en/storagegrid-115/[StorageGRID 11.5 docs^]
* https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61023[StorageGRID 11.4 docs^]

== StorageGRID appliances

* https://docs.netapp.com/us-en/storagegrid-appliances/[StorageGRID appliances^]

== How to enable StorageGRID in your environment

Go to https://docs.netapp.com/us-en/storagegrid-enable/index.html[How to enable StorageGRID in your environment^] to learn how to test and enable applications in your StorageGRID environment.

The *storagegrid-enable* documentation site provides examples and cookbooks that expand upon the product documentation in this site, and it describes some next steps in evaluating and integrating with StorageGRID.

Some of the information included:

* Lists of validated third-party solutions for past and current StorageGRID releases.

* Product feature guides. For example, these guides provide all the information you need to create Cloud Storage Pools.

* Tool and application guides.

* API examples for using StorageGRID features such as S3 encryption and S3 Object Lock.

