---
permalink: intro-family.html
keywords: storagegrid
summary: NetApp StorageGRID is a software-defined object storage suite that supports a wide range of use cases across public, private, and hybrid multicloud environments. StorageGRID offers native support for the Amazon S3 API and delivers industry-leading innovations such as automated lifecycle management to store, secure, protect, and preserve unstructured data cost effectively over long periods.
---
= Learn about StorageGRID
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
NetApp StorageGRID is a software-defined object storage suite that supports a wide range of use cases across public, private, and hybrid multicloud environments. StorageGRID offers native support for the Amazon S3 API and delivers industry-leading innovations such as automated lifecycle management to store, secure, protect, and preserve unstructured data cost effectively over long periods.

== StorageGRID software

* https://review.docs.netapp.com/us-en/storagegrid-118_main/[StorageGRID 11.8 docs^]
* https://review.docs.netapp.com/us-en/storagegrid-117_main/[StorageGRID 11.7 docs^]
* https://docs.netapp.com/us-en/storagegrid-116/[StorageGRID 11.6 docs^]

== StorageGRID appliances

* https://review.docs.netapp.com/us-en/storagegrid-appliances_main/[StorageGRID appliances^]

== How to enable StorageGRID in your environment

Go to https://docs.netapp.com/us-en/storagegrid-enable/index.html[How to enable StorageGRID in your environment^] to learn how to test and enable applications in your StorageGRID environment.

The *storagegrid-enable* documentation site provides examples and cookbooks that expand upon the product documentation in this site, and it describes some next steps in evaluating and integrating with StorageGRID.

Some of the information included:

* Lists of validated third-party solutions for past and current StorageGRID releases.

* Product feature guides. For example, these guides provide all the information you need to create Cloud Storage Pools.

* Tool and application guides.

* API examples for using StorageGRID features such as S3 encryption and S3 Object Lock.
