settings:
  name: StorageGRID
  search: "storagegrid,appliances,hardware,object storage"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
# harmony_enabled: true
sidebar:
  entries:
    - title: StorageGRID product documentation
      url: /index.html
product-family:
  sidebarlinks:
      - title: All
        tags: all
        class: active
      - title: Get started
        tags: get_started
      - title: StorageGRID software
        tags: storagegrid
      - title: Appliances
        tags: appliances
      - title: Enable StorageGRID
        tags: enable
  tiles:
      - title: "Learn about StorageGRID"
        icon: ./media/groups_line-1.png
        url: /intro-family.html
        summary: "Learn about the E-Series family of storage systems."
        tags: all, get_started
