settings:
  name: StorageGRID
  search: "storagegrid,appliances,hardware,object storage"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
# harmony_enabled: true
sidebar:
  entries:
    - title: StorageGRID product documentation
      url: /index.html
product-family:
  sidebarlinks:
    - title: All
      tags: tag_get_started, tag_storagegrid, tag_appliances, tag_enable
      class: active
    - title: Get started
      tags: tag_get_started
    - title: StorageGRID software
      tags: tag_storagegrid
    - title: Appliances
      tags: tag_appliances
    - title: Enable StorageGRID
      tags: tag_enable
