settings:
  name: StorageGRID
  search: "storagegrid-enable,storagegrid,storagegrid-appliances"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: true
sidebar:
  entries:
    - title: StorageGRID product documentation
      url: /index.html
