settings:
  name: "StorageGRID"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
#    harmony_enabled: true

sidebar: 
  entries:
  - title: About
    url: /index.html
  - title: Legal notices
    url: /legal-notices.html