settings:
  name: StorageGRID
# search: "storagegrid,appliances,hardware,object storage"
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
sidebar:
  entries:
    - title: StorageGRID product documentation
      url: /index.html
    - title: StorageGRID product documentation 
      url: /legal-notices.html  
product-family:
  sidebarlinks:
      - title: All
        tags: all
        class: active
      - title: Get started
        tags: get_started
      - title: StorageGRID software
        tags: storagegrid
      - title: Appliances
        tags: appliances
      - title: Enable StorageGRID
        tags: enable
    
  tiles:
      - title: "Learn about StorageGRID"
        icon: ./media/groups_line.png
        url: intro-family.html
        summary: "Learn about StorageGRID documentation."
        tags: all, get_started
      - title: "StorageGRID 11.8 software"
        icon: ./media/config_line.png
        url: https://review.docs.netapp.com/us-en/storagegrid-118_main/index.html
        summary: "Use StorageGRID documentation."
        tags: all, storagegrid
      - title: "StorageGRID appliances"
        icon: ./media/server.png
        url: https://review.docs.netapp.com/us-en/storagegrid-appliances_main/index.html
        summary: "Install and maintain StorageGRID appliances."
        tags: all, appliances
      - title: "Enable StorageGRID"
        icon: ./media/synergy.png
        url: https://docs.netapp.com/us-en/storagegrid-enable/index.html
        summary: "Install and maintain StorageGRID appliances."
        tags: all, enable